version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: stock_prediction_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - db_data:/app/database
    environment:
      - SECRET_KEY=9a6e30b62e49c7bc29ca7e9e38e6e580e5b87ccb9f71c4c1a5d62908f0a0d611
      - ALGORITHM=HS256
      - DATABASE_URL=sqlite:///./stock_platform.db
      - HOST=0.0.0.0
      - PORT=8000
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: stock_prediction_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

volumes:
  db_data:
